Demoscopesis/urls.py
from Demoscopesis import views
from django.urls import re_path
from django.contrib import admin

app_name = 'Demoscopesis'
urlpatterns = [
	#/Demoscopesis/
	re_path(r'^$', views.index, name='index'),
	#/Demoscopesis/5/
	re_path(r'^(?P<polls_id>[0-9]+)/$', views.moreInfo, name='moreInfo'),
	#/Demoscopesis/5/vote
	re_path(r'^(?P<polls_id>[0-9]+)/vote/$', views.vote, name='vote'),
	#/Demoscopesis/create
	re_path(r'^create/$', views.createPoll, name='createPoll'),
	#/Demoscopesis/edit/5/
	#re_path(r'^/edit/(?P<polls_id>[0-9]+)/$', views.edit, name='edit'),
]

admin.site.site_header = 'Epitome administration'
admin.site.site_title = 'Epitome administration'
admin.site.index_title = 'Home'

Epitome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Agora import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import RedirectView
from django.urls import path

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'^home/', views.homePage, name='home'),
    #url(r'^user/', include('Propylaea.urls', namespace="Propylaea")),
    #url(r'^demoscopesis/', include('demoscopesis.urls', namespace="demoscopesis")),
    #url(r'^.*/$', RedirectView.as_view(url='/home/')),
    #url(r'^$', RedirectView.as_view(url='/home/'))
	
	path('admin/', admin.site.urls),
	path('about/', views.aboutPage, name='about'),
	path('user/', include('Propylaea.urls', namespace='Propylaea')),
	path('demoscopesis/', include('Demoscopesis.urls', namespace='Demoscopesis')),
	url(r'^.*/$', RedirectView.as_view(url='/demoscopesis/')),
    url(r'^$', RedirectView.as_view(url='/demoscopesis/')),
]

urlpatterns += staticfiles_urlpatterns()

Demoscopesis/models.py
#from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, Group


class PollCat(models.Model):
	PCAT_CAT = models.CharField("Poll category", max_length=100)                                         # the category of the poll
	def __str__(self):
		return self.PCAT_CAT
	class Meta:
		verbose_name = 'Poll category'
		verbose_name_plural = 'Poll categories'


class Poll(models.Model):
	PL_CODE = models.CharField("Code", max_length=200)                                                   # the code of the poll
	PL_TITLE = models.CharField("Title", max_length=200)                                                 # the title of the poll
	PL_SHRBODY = models.CharField("Short body", max_length=300)                                          # the short body of the poll
	PL_BODY = models.CharField("Body", max_length=1000)                                                  # the body (main text) of the poll
	PL_CREATION = models.DateTimeField("Creation date", default = timezone.now)                          # the creation date and time of the poll
	PL_STARTDT = models.DateTimeField("Starting date")                                                   # the starting date and time of the poll
	PL_ENDDT = models.DateTimeField("Ending date")                                                       # the ending date and time of the poll
	PL_DURATION = models.IntegerField("Duration", default=0)                                             # the duration of the poll
	PL_CODE2 = models.CharField("Code 2", max_length=200, blank = True)                                  # the code2 of the poll (protocol number, approval number)
	USER = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="User")                        # the user (admin) who created the poll
	UGROUP = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name="User group")               # the group of the user that created the poll
	POLLCAT = models.ForeignKey(PollCat, on_delete=models.CASCADE, verbose_name="Poll category")         # the category of the poll
	def __str__(self): 
		return "%s %s" % (self.PL_TITLE, self.PL_SHRBODY)


class PollChoice(models.Model):
	POLL = models.ForeignKey(Poll, related_name='PChoice', on_delete=models.CASCADE)                     # key to Polls table
	PC_CHOICE = models.CharField("Choice", max_length=100)                                               # the vote choice
	PC_VOTES = models.IntegerField("Votes", default=0)                                                   # the number of votes
	def __str__(self):
		return self.PC_CHOICE


class Voter(models.Model):
	USER = models.ForeignKey(User, on_delete=models.CASCADE)
	POLL = models.ForeignKey(Poll, on_delete=models.CASCADE)


class Issue(models.Model):
	IS_CODE = models.CharField("Code", max_length=200)                                                   # the code of the issue
	IS_TITLE = models.CharField("Title", max_length=200)                                                 # the title of the issue
	IS_SHRBODY = models.CharField("Short body", max_length=300)                                          # the short body of the issue
	IS_BODY = models.CharField("body", max_length=1000)                                                  # the body (main text) of the issue
	IS_CREATION = models.DateTimeField("Creation date", default = timezone.now)                          # the creation date and time of the issue
	IS_CODE2 = models.CharField("Code 2", max_length=200, blank = True)                                  # the code2 of the issue (protocol number, approval number)
	USER = models.ForeignKey(User, on_delete=models.CASCADE)                                             # the user (admin) who created the issue
	UGROUP = models.ForeignKey(Group, on_delete=models.CASCADE)                                          # the group of the user that created the issue
	def __str__(self): 
		return "%s %s" % (self.IS_TITLE, self.IS_SHRBODY)


class Evidence(models.Model):
	EV_FLD1 = models.CharField(max_length=1000)                                                          # What has happened?
	EV_FLD2 = models.CharField(max_length=1000)                                                          # Why is it important?
	EV_FLD3 = models.CharField(max_length=1000)                                                          # Who has been affected?
	EV_FLD4 = models.CharField(max_length=1000)                                                          # How and why did it happen?
	EV_FLD5 = models.CharField(max_length=1000)                                                          # Where did it occur?
	EV_FLD6 = models.CharField(max_length=1000)                                                          # When did it occur?
	EV_FLD7 = models.CharField(max_length=1000)                                                          # How much is the cost?
	EV_FLD8 = models.CharField(max_length=1000)                                                          # How long did it last?
	ISSUE = models.ForeignKey(Issue, on_delete=models.CASCADE)                                           # key to Issues table

Demoscopesis/forms.py
from django import forms
from django.forms import ModelForm, Textarea, modelform_factory
from Demoscopesis.models import Poll, PollChoice

class PollForm(ModelForm):
	class Meta:
		model = Poll
		fields = ('PL_TITLE', 'PL_SHRBODY', 'PL_BODY', 'PL_STARTDT', 'PL_ENDDT', 'PL_CODE', 'POLLCAT')
		widgets = {
			'PL_CODE' : forms.TextInput(attrs={'type':'text','id':'code','class':'form-control','required': True}),
			'PL_TITLE' : forms.TextInput(attrs={'type':'text','id':'title','class':'form-control','required': True}),
			'PL_SHRBODY' : Textarea(attrs={'id':'shortbody','class':'form-control','rows':'3', 'required': True, 'autofocus':True}),
			'PL_BODY' : Textarea(attrs={'id':'body','class':'form-control','rows':'10', 'required': True, 'autofocus':True}),
			'PL_STARTDT' : forms.TextInput(attrs={'type':'date','id':'startdate','class':'form-control','required': True}),
			'PL_ENDDT' : forms.TextInput(attrs={'type':'date','id':'enddate','class':'form-control','required': True}),
			'POLLCAT' : forms.TextInput(attrs={'type':'text','id':'category','class':'form-control','required': True})
		}

class PollChoiceForm(ModelForm):
	class Meta:
		model = PollChoice
		fields = ('PC_CHOICE',) # Fields is not a String, comma is needed.
		widgets = {
			'PC_CHOICE' : forms.TextInput(attrs={'type':'hidden', 'id':'payload' ,'class':'form-control','required': True})
		}
		
PollChoiceFormSet = modelform_factory(PollChoice, form=PollChoiceForm)

Demoscopesis/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages
from Demoscopesis.forms import PollForm, PollChoiceFormSet

from .models import Poll, PollChoice, Voter

@login_required(login_url='/user/login/')
def index(request):
	latest_poll_list = Poll.objects.order_by('-PL_CREATION')
	template = loader.get_template('Demoscopesis/index.html')
	context = {
		'latest_poll_list': latest_poll_list,
	}
	return HttpResponse(template.render(context, request))
	
@login_required(login_url='/user/login/')
def createPoll(request):
	if request.method == 'POST':
		context = {
			'PollForm': PollForm,
			'PollChoiceFormSet' : formSet,
		}
		return HttpResponse(template.render(context, request))
	else:
		formSet = PollChoiceFormSet
		template = loader.get_template('Demoscopesis/poll-edit.html')
		context = {
			'PollForm': PollForm,
			'PollChoiceFormSet' : formSet,
		}
		return HttpResponse(template.render(context, request))

@login_required(login_url='/user/login/')
def moreInfo(request, polls_id):
	poll = get_object_or_404(Poll, pk=polls_id)
	template = loader.get_template('Demoscopesis/poll.html')
	nowDt = timezone.localtime(timezone.now())
	context = {
		'poll': poll,
		'nowdt': nowDt,
	}
	return HttpResponse(template.render(context, request))

@login_required(login_url='/user/login/')
def vote(request, polls_id):
	poll = get_object_or_404(Poll, pk=polls_id)
	if Voter.objects.filter(POLL_id=polls_id, USER_id=request.user.id).exists():
		messages.add_message(request, messages.INFO, 'You have already voted.')
		return HttpResponseRedirect(reverse('Demoscopesis:index'))
	else:
		try:
			selected_choice = poll.PChoice.get(pk=request.POST['choice'])
		except (KeyError, PollChoice.DoesNotExist):						#probably wrong
			# Redisplay the question voting form.
			nowDt = timezone.localtime(timezone.now())
			return render(request, 'Demoscopesis/poll.html', {
				'poll': poll,
				'nowdt': nowDt,
				'error_message': "Please select a choice.",
			})
		else:
			selected_choice.PC_VOTES += 1
			selected_choice.save()
			v = Voter(USER=request.user, POLL=poll)
			v.save()
			# Always return an HttpResponseRedirect after successfully dealing
			# with POST data. This prevents data from being posted twice if a
			# user hits the Back button.
			messages.add_message(request, messages.INFO, 'Vote submited successfully.')
			return HttpResponseRedirect(reverse('Demoscopesis:index'))#, args=(poll.id,)))

Demoscopesis/templates/Demoscopesis/index.html
{% extends '_base.html' %} 
{% load static %} 

{% block body %}
<div id="wrapper">

    {% include '_sidebar.html' %}

    {% include '_navbar.html' %} 

    <div id="page-content-wrapper">
        {% if messages %} 
            {% for message in messages %}
            <div class="alert alert-success" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>
                    <p>{{ message }}</p>
                </strong>
            </div>
            {% endfor %} 
        {% endif %}

        <div class="container">
            {% if latest_poll_list %}
            <div class="card-columns">
                {% for poll in latest_poll_list %}
                <a href="/demoscopesis/{{ poll.id }}/">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ poll.PL_TITLE }}</h5>
                            <p class="text-dark">{{ poll.PL_SHRBODY }}</p>
                            <p class="card-text">
                                <small class="text-muted">Created by: {{ poll.USER }}</small>
                            </p>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
            {% else %}
            <div class="container">
                <div class="jumbotron">
                    <h1 class="display-3">No polls were found.</h1>
                    <p class="lead">No polls were submitted so far.</p>
                    <hr class="my-4">
                    <p>Try visiting another section or add a poll yourself.</p>
                    <p class="lead">
                        <a class="btn btn-primary btn-lg" href="/demoscopesis/create/" role="button">Add a poll</a>
                    </p>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %} 


{% block scripts %}
<script src="{% static "js/jquery-3.3.1.min.js"%}"></script>
<script src="{% static "js/jquery.formset.min.js"%}"></script>
<script src="{% static "js/bootstrap.bundle.min.js"%}"></script>
<script src="{% static "js/sidebar.js"%}"></script>
{% endblock %}

Demoscopesis/templates/Demoscopesis/poll-edit.html
{% extends '_base.html' %} 
{% load static %} 

{% block body %}
        <div id="wrapper">

                {% include '_sidebar.html' %}
            
                {% include '_navbar.html' %}

            <div id="page-content-wrapper">
                <div class="container">

                    <!-- Modal -->
                    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalCenterTitle">Too few options!</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
                            <div class="modal-body">
                            You need at least 2 options for people to vote on.
                            </div>
                            <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                        </div>
                    </div>

                    <div class="mb-3">
                        <h2 class="text-center"><b>Poll Creation</b></h2>
                    </div>

                    <form id="form-body" action="{% url 'Demoscopesis:createPoll' %}" method="post" class="poll-form" role="form" data-parsley-validate novalidate>
						{% csrf_token %}
                        <div class="container-fluid shadow py-5">
                            <div class="row">            
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>Title</b></label>
                                        <div id="title" class="controls">
                                            {{ PollForm.PL_TITLE }} 
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>Short Body</b></label>
                                        <div id="shBody" class="controls">
                                            {{ PollForm.PL_SHRBODY }} 
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>Body</b></label>
                                        <div id="body" class="controls">
                                            {{ PollForm.PL_BODY }} 
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>Start Date</b></label>
                                        <div id="startDt" class="controls">
                                            {{ PollForm.PL_STARTDT }} 
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>End Date</b></label>
                                        <div id="endDt" class="controls">
                                            {{ PollForm.PL_ENDDT }} 
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>Code</b></label>
                                        <div id="code" class="controls">
                                            {{ PollForm.PL_CODE }} 
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label control-label-left col-sm-3" for="field2"><b>Category</b></label>
                                        <div id="category" class="controls">
                                            {{ PollForm.POLLCAT }} 
                                        </div>
                                    </div>
                                    <hr />
                                    <div class="form-group">
                                        <div class="row">
                                            <div class="col-6">
                                                <label class="control-label control-label-left float-left mx-3"><b>Voting Choices</b></label>
                                            </div>
                                            <div class="col-6"|>
                                                <button id="add" type="button" class="btn btn-outline-info float-right" onclick="addOption()"><b>+</b></button>
                                            </div>
                                        </div>
                                        
                                        <div id="choice" class="controls mt-3">
                                            {{ PollChoiceFormSet }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="form-group text-center mt-3">
                        <div class="form-group text-center">
                            <button id="submit" type="button" class="btn btn-success" onclick="submitAll()">Submit</button>
                            <button id="cancel" type="button" class="btn btn-danger" onclick="window.history.back()">Cancel</button>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %} 


{% block scripts %}
<script src="{% static "js/jquery-3.3.1.min.js"%}"></script>
<script src="{% static "js/jquery.formset.min.js"%}"></script>
<script src="{% static "js/bootstrap.bundle.min.js"%}"></script>
<script src="{% static "js/poll-edit.js"%}"></script>
<script src="{% static "js/sidebar.js"%}"></script>
{% endblock %}

Demoscopesis/templates/Demoscopesis/poll.html
{% extends '_base.html' %} 
{% load static %} 

{% block body %}
<div id="wrapper">

    {% include '_sidebar.html' %}

    {% include '_navbar.html' %}  
    
    {% if poll.PL_ENDDT > nowdt %}
    <form action="{% url 'Demoscopesis:vote' poll.id %}" method="post">
        <div id="page-content-wrapper">
            <div class="container">
                <div class="card mt-3">
                    <div class="card-header">
                        <h4>Created by: {{ poll.USER }}
                            <span></span> on: {{ poll.PL_STARTDT }}</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title">{{ poll.PL_TITLE }}</h1>
                        <h3>Subtitle</h3>
                        <p class="card-text">{{ poll.PL_BODY }}</p>
                    </div>
                    <div class="card-footer text-center">
                        {% csrf_token %} {% for choice in poll.PChoice.all %}
                        <button type="submit" name="choice" class="btn btn-outline-primary" value="{{ choice.id }}">{{ choice.PC_CHOICE }}</button>
                        {% endfor %}
                        <a class="btn btn-danger" href="/demoscopesis" role="button">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </form>

    {% else %}

    <div id="page-content-wrapper">
        <div class="container">
            <div class="card">
                <div class="card-header text-center">
                    <h4>Results</h4>
                </div>
                <div class="card-body">
                    {% for choice in poll.PChoice.all %}
                    <h4>{{ choice.PC_CHOICE }}</h4>
                    <div class="progress">
                        <div class="progress-bar bg-danger" role="progressbar" style="width: 50%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    {% endfor %}
                </div>
                <div class="card-footer text-center">
                    <h4>Total number of voters:
                        <span class="text-danger">50</span>
                    </h4>
                </div>
            </div>

            <div class="card mt-3">
                <div class="card-header">
                    <h4>Created by: {{ poll.USER }}
                        <span></span>, on {{ poll.PL_STARTDT }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title">{{ poll.PL_TITLE }}</h1>
                    <p class="card-text">{{ poll.PL_BODY }}</p>
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %} 

{% block scripts %}
<script src="{% static "js/jquery-3.3.1.min.js"%}"></script>
<script src="{% static "js/jquery.formset.min.js"%}"></script>
<script src="{% static "js/bootstrap.bundle.min.js"%}"></script>
<script src="{% static "js/sidebar.js"%}"></script>
{% endblock %}